# Generated by Django 4.1 on 2024-03-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impute_model", models.CharField(max_length=10)),
                ("predict_model", models.CharField(max_length=10)),
                ("perdict_batch_size", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="TrainParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impute_model", models.CharField(max_length=10)),
                ("predict_model_choice", models.TextField()),
                ("train_batch_size", models.FloatField()),
                ("predict_data_Batch_size", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="TrainResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=20)),
                ("time", models.TimeField()),
                ("accuracy", models.FloatField()),
                ("precision", models.FloatField()),
                ("SMAPE", models.FloatField()),
            ],
        ),
    ]
