# Generated by Django 4.1 on 2024-03-14 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="impute_model",
        ),
    ]
