# Generated by Django 4.1 on 2024-03-18 03:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0002_remove_task_impute_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="perdict_batch_size",
            new_name="predict_batch_size",
        ),
    ]
