# Generated by Django 4.1 on 2024-03-25 02:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0005_remove_trainparameters_predict_data_batch_size_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TrainParameters",
        ),
    ]
