# Generated by Django 4.1 on 2024-03-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0006_delete_trainparameters"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impute_model", models.TextField()),
                ("predict_model", models.TextField()),
                ("train_data_size", models.FloatField()),
                ("predict_window_size", models.FloatField()),
                ("imputation_size", models.FloatField()),
                (
                    "dataset",
                    models.FileField(
                        max_length=128, upload_to="dataset/", verbose_name="dataset"
                    ),
                ),
            ],
        ),
    ]
