# Generated by Django 4.1 on 2024-03-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0008_trainresult_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="impute_model",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
