# Generated by Django 4.1 on 2024-03-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0009_task_impute_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="predict_batch_size",
            new_name="predict_window_size",
        ),
        migrations.AlterField(
            model_name="task",
            name="impute_model",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="task",
            name="predict_model",
            field=models.CharField(max_length=20),
        ),
    ]
