# Generated by Django 4.1 on 2024-03-26 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0011_predictionresult"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PredictionResult",
            new_name="PredictResult",
        ),
    ]
