# Generated by Django 4.1 on 2024-03-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0012_rename_predictionresult_predictresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictresult",
            name="is_Anomaly",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
